version: '3.8'
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  app:
    build: .
    volumes:
      - ./watched:/app/watched
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 8000:8000
